name: Generate Snake Animation

on:
  schedule:
    # Executa uma vez por dia
    - cron: "0 0 * * *"
  push:
    # Executa sempre que algo for alterado no repositório
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório
      - uses: actions/checkout@v3

      # Cria o diretório de saída caso não exista
      - name: Create output directory
        run: mkdir -p dist

      # Gera a animação da cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ThiagooSantoss
          outputs: dist/snake.svg

      # Cria um Pull Request com as alterações
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Atualiza animação da cobrinha"
          title: "Atualiza animação da cobrinha"
          body: "Este PR atualiza a animação da cobrinha gerada automaticamente."
          branch: "update-snake-animation"
          delete-branch: true
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
